name: trigger
on:
    push:
        branches:
            - master 
    pull_request:
    workflow_dispatch:

jobs:
    trigger-demo:
        runs-on: ubuntu-latest 
        steps:
            - run: echo "hello"
            






        